name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Zip build
        working-directory: ${{ github.workspace }}/addons/brisklance/self
        run: zip -r ${{ github.workspace }}/brisklance_module.zip ./*

      - name: Export build
        uses: actions/upload-artifact@v4
        with:
          name: brisklance_module
          path: ${{ github.workspace }}/brisklance_module.zip
          if-no-files-found: error
